[dbserver]
dbms = "mysql"
user = "twigolu"
pass = "possible"
protocol = "tcp(127.0.0.1:3306)"
dbname = "twigoludb"
charset = "charset=utf8mb4"
parsetime = "parseTime=true&loc=Asia%2FTokyo"

[apserver]
numperpage = 10
origin = "http://127.0.0.1:3000"
port = ":9001"
cookie_key = "twigolucookie"
salt = "nex777ad"
