[dbserver]
dbms = "mysql"
user = "twigolu"
pass = "possible"
protocol = "tcp(127.0.0.1:3306)"
dbname = "twigoludb"
charset = "charset=utf8mb4"
parsetime = "parseTime=true&loc=Asia%2FTokyo"

[apserver]
numperpage = 10
origin = ["http://127.0.0.1:3000","http://192.168.61.6:3000","http://192.168.61.7:3000"]
port = ":9001"
cookie_key = "twigolucookie"
salt = "nex777ad"
cs_key = "zPc3DzlRHnsrByWyOz5QbyEEq"
cs_secret_key = "EUJDVaUB6KHX5jpW1VMwZacOSLtxRfxy0cRD47F780kaYbiYR6"
